//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonner
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datedebut { get; set; }
        public Nullable<System.DateTime> datefin { get; set; }
        public Nullable<int> idmembere { get; set; }
        public Nullable<int> idabonnement { get; set; }
    
        public virtual type_abonnement type_abonnement { get; set; }
        public virtual membere membere { get; set; }
    }
}
