//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class coach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coach()
        {
            this.sports = new HashSet<sport>();
        }
    
        public int id_coach { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string numero { get; set; }
        public string sexe { get; set; }
        public string nom_sport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sport> sports { get; set; }
    }
}
