//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class offrir
    {
        public int id_offrire { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> numsalle { get; set; }
        public Nullable<int> numsport { get; set; }
    
        public virtual salle salle { get; set; }
        public virtual sport sport { get; set; }
    }
}
