//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Gym
{
    using System;
    using System.Collections.Generic;
    
    public partial class participer
    {
        public int id_participer { get; set; }
        public Nullable<int> idsport { get; set; }
        public Nullable<int> idmembere { get; set; }
    
        public virtual membere membere { get; set; }
        public virtual sport sport { get; set; }
    }
}
